**Name:  Anjali Arvind Shirke**    
**Roll No : 07**    
**Assignment 9**   

### Aim
Write a python program to design a Hopfield Network which stores 4 vectors.

### Step 1: Import Required Packages

In [1]:
import numpy as np

### Step 2: Define the Hopfield Network Class
- `train()` computes the weight matrix from training patterns using Hebb's rule.
- `recall()` takes a (possibly noisy) input and iterates until the network converges to a stored pattern.

In [2]:
class HopfieldNetwork:
    def __init__(self):
        self.W = None

    def train(self, patterns):
        """Learn the weight matrix from binary patterns using Hebb's rule."""
        n = patterns.shape[1]
        self.W = np.zeros((n, n))
        for p in patterns:
            p_bipolar = 2 * p - 1  # Convert binary (0,1) to bipolar (-1,+1)
            self.W += np.outer(p_bipolar, p_bipolar)
        np.fill_diagonal(self.W, 0)  # No self-connections
        print('Weight matrix W:')
        print(self.W)

    def recall(self, pattern, max_steps=100):
        """Recall a stored pattern from a (possibly noisy) input."""
        x = 2 * pattern - 1  # Convert binary (0,1) to bipolar (-1,+1)
        for step in range(max_steps):
            x_new = x.copy()
            for i in range(len(x)):
                net_input = np.dot(self.W[i], x)
                x_new[i] = 1 if net_input >= 0 else -1
            if np.array_equal(x, x_new):
                print(f'  Converged in {step + 1} step(s)')
                break
            x = x_new
        return (x + 1) // 2  # Convert back to binary

Training :
* **Hebb's Rule for Weights:** For each pattern p, add np.outer(p_bipolar, p_bipolar) (outer product: a matrix where W[i][j] = p_bipolar[i] * p_bipolar[j]).
* **Total Weight Matrix:** W = Σ (outer products), then set diagonal to 0 (no self-feedback).

Recall :
* **Update Rule:** For each neuron i: net_input = Σ W[i][j] * x[j] (weighted sum), then x_new[i] = sign(net_input) (1 if >=0, -1 if <0).

### Step 3: Define 4 Binary Patterns to Store

In [3]:
# patterns = np.array([
#     [1, 0, 1, 0],
#     [1, 1, 0, 0],
#     [0, 1, 0, 1],
#     [0, 0, 1, 1],
# ])
patterns = np.array([
    [1,0,0,0,1,0,0,0],  # Pattern A
    [0,1,0,0,0,1,0,0],  # Pattern B
    [0,0,1,0,0,0,1,0],  # Pattern C
    [0,0,0,1,0,0,0,1],  # Pattern D
])

print('Stored patterns:')
for i, p in enumerate(patterns):
    print(f'  Pattern {i}: {p}')

Stored patterns:
  Pattern 0: [1 0 0 0 1 0 0 0]
  Pattern 1: [0 1 0 0 0 1 0 0]
  Pattern 2: [0 0 1 0 0 0 1 0]
  Pattern 3: [0 0 0 1 0 0 0 1]


### Step 4: Train the Hopfield Network

In [4]:
hop = HopfieldNetwork()
hop.train(patterns)

Weight matrix W:
[[0. 0. 0. 0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0. 0. 0. 0.]
 [0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0.]]


### Step 5: Test Recall with Stored Patterns
Verify that the network can perfectly recall each stored pattern.

In [5]:
print('Recall of stored patterns:')
for i, p in enumerate(patterns):
    recalled = hop.recall(p)
    match = 'YES' if np.array_equal(p, recalled) else 'NO'
    print(f'  Input: {p}  ->  Recalled: {recalled}  Match: {match}')

Recall of stored patterns:
  Converged in 1 step(s)
  Input: [1 0 0 0 1 0 0 0]  ->  Recalled: [1 0 0 0 1 0 0 0]  Match: YES
  Converged in 1 step(s)
  Input: [0 1 0 0 0 1 0 0]  ->  Recalled: [0 1 0 0 0 1 0 0]  Match: YES
  Converged in 1 step(s)
  Input: [0 0 1 0 0 0 1 0]  ->  Recalled: [0 0 1 0 0 0 1 0]  Match: YES
  Converged in 1 step(s)
  Input: [0 0 0 1 0 0 0 1]  ->  Recalled: [0 0 0 1 0 0 0 1]  Match: YES


### Step 6: Test Recall with Noisy Input
Feed a corrupted/noisy version of a pattern and see if the network recovers the original.

In [6]:
# noisy_input = np.array([1, 0, 0, 0])
# print(f'Noisy input:    {noisy_input}')
# recalled = hop.recall(noisy_input)
# print(f'Recalled pattern: {recalled}')

# Noisy input based on Pattern C
noisy = np.array([0,0,1,0,0,0,0,0])  # flip half of C toward neutral
print("Noisy input:", noisy)
recalled = hop.recall(noisy)
print("Recalled:", recalled)

dists = [np.sum(np.abs(recalled - p)) for p in patterns]
print("\nHamming distances:", dists, "closest index =", np.argmin(dists))

closest_pattern = patterns[np.argmin(dists)]
print("Closest Pattern for Recall:", closest_pattern)

Noisy input: [0 0 1 0 0 0 0 0]
Recalled: [0 0 1 0 0 0 0 0]

Hamming distances: [np.int64(3), np.int64(3), np.int64(1), np.int64(3)] closest index = 2
Closest Pattern for Recall: [0 0 1 0 0 0 1 0]
