**Name:  Anjali Arvind Shirke**    
**Roll No : 07**    
**Assignment 9**   

### Aim
Write a python program to design a Hopfield Network which stores 4 vectors.

In [1]:
import numpy as np

In [2]:
class HopfieldNetwork:

    def __init__(self):
        self.weights = None

    def train(self, patterns):
        num_neurons = patterns.shape[1]
        self.weights = np.zeros((num_neurons, num_neurons))

        for p in patterns:
            self.weights += np.outer(p, p)

        np.fill_diagonal(self.weights, 0)  # No self-connection

        print("Training completed. Weight matrix:")
        print(self.weights)

    def recall(self, pattern, steps=5):
        output = pattern.copy()
        print(f"\nStarting recall for pattern: {pattern}")

        for step in range(steps):
            output = np.sign(self.weights @ output)
            print(f"Step {step+1}: {output}")

        return output

In [3]:
# Helper: Convert binary (0,1) to bipolar (-1,1)
def to_bipolar(binary_pattern):
    return np.where(binary_pattern == 0, -1, 1)

In [4]:
# Training patterns (4 vectors, each with 6 bits)
binary_patterns = np.array([
    [1, 0, 1, 0, 1, 0],
    [1, 1, 0, 0, 1, 0],
    [0, 1, 0, 1, 0, 1],
    [1, 0, 0, 1, 1, 0]
])

In [5]:
# Convert to bipolar form
bipolar_patterns = np.array([to_bipolar(p) for p in binary_patterns])

# Create and train the Hopfield Network
hopfield = HopfieldNetwork()
hopfield.train(bipolar_patterns)

Training completed. Weight matrix:
[[ 0. -2.  0. -2.  4. -4.]
 [-2.  0. -2.  0. -2.  2.]
 [ 0. -2.  0. -2.  0.  0.]
 [-2.  0. -2.  0. -2.  2.]
 [ 4. -2.  0. -2.  0. -4.]
 [-4.  2.  0.  2. -4.  0.]]


In [6]:
# Test pattern (with slight noise)
test_pattern = to_bipolar(np.array([1, 0, 1, 0, 0, 0]))

In [7]:
# Recall
recalled = hopfield.recall(test_pattern)

print("\nFinal Recalled Pattern:", recalled)


Starting recall for pattern: [ 1 -1  1 -1 -1 -1]
Step 1: [ 1. -1.  1. -1.  1. -1.]
Step 2: [ 1. -1.  1. -1.  1. -1.]
Step 3: [ 1. -1.  1. -1.  1. -1.]
Step 4: [ 1. -1.  1. -1.  1. -1.]
Step 5: [ 1. -1.  1. -1.  1. -1.]

Final Recalled Pattern: [ 1. -1.  1. -1.  1. -1.]
